#!/bin/sh

# Store the current working directory
CWD=$(pwd)

# Stash any changes not being committed
git stash -q --keep-index

echo "Running prettier..."
# Run prettier on staged files
bun prettier --write $(git diff --cached --name-only --diff-filter=d | grep -E '\.(js|jsx|ts|tsx|json|css|scss|md)$')

# Add the prettified files back to staging
git add $(git diff --cached --name-only --diff-filter=d | grep -E '\.(js|jsx|ts|tsx|json|css|scss|md)$')

# Restore stashed changes
git stash pop -q

echo "✅ Code formatting complete!"
exit 0 